### ISSUE TITLE
Multiple payment addresses

### ISSUE THREAD

**Issue by faneaatiku** [faneaatiku/s-nomp#4]
add multiple payment addresses for coins that require shielding. 

This would help the payment processor to keep up with payments. 

be careful one daemon load while doing this.

**Comment by egyptianbman** [comment]
I'm not sure what you mean by this.

**Comment by faneaatiku** [comment]
As we know when a transaction is sent the remaining unspent is sent to another address thus creating a new tx. When the payment processor runs again if that tx doesn’t meet the minimum confirmation requirements it can’t be spent on payments.

I was thinking if it’s possible to unshield the exact max amount that a payment can use (maxBlocksPerPayment * block subsidy) to multiple addresses instead of one. 
The general purpose is to avoid payment processor running for nothing. 

Another thing would be to make “maxBlocksPerPayment” to behave like MAX, at the moment it’s working like “blocksPerPayment”. You need to have the amount for all blocks. But this is another issue, i’ll create it later.

**Comment by egyptianbman** [comment]
I think I see what you mean. One solution would be to calculate the remainder and add that to the transaction to be routed back to the payout address (instead of a random address that has to then be sent back to the payout address to be paid)

**Comment by egyptianbman** [comment]
I think the remainder is based on block reward? It's been a long time since I've looked into that but let's take BTCZ as an example.

If you have 2 miners, each getting 500 btcz from a block, you would send 1k to the miners, then 11500 back to the payout address. This ensures minimum number of transactions between payouts.

**Comment by egyptianbman** [comment]
Another option is to just take the full value of the payout address and send it back as a remainder.

Say you have 5k coins in the payout address and you're making a payout to miners for 1k. You would send 1k to the miners then 4k back to the payout address. Again, this would keep you from having to make a tx to a random address then sending back to the payout address.

**Comment by faneaatiku** [comment]
IMHO sending back to the same address doesn't help as it's still a transaction that needs X confirmations to be used for the next payment (min 3 confirmations). 

Still with BTCZ as example: 

1. Shielding is done - let's say 3 generated blocks go to Z address
2. after 3 confirmations all the amount(37500 btcz) is sent to payment address
3. we have maxBlocksPerPayment = 1
4. From t address miners are paid 1 block (12500) -> the remaining amount is sent to a random address. 

case 1-> sending the remainder to the same address: 
- this wouldn't solve anything. If the paymentProcessor runs again in 120 seconds, the remainder wouldn't be confirmed yet. Leading to "Insufficient funds" error, and this leads to the delay mentioned above. 
- this is exactly as sending to a random address, because when payments are done it uses sendmany method. So it sends funds from any address available in the wallet. 

case 2 -> sending the reminder to another 2 addresses:
- we have 3 blocks to pay, 12500 each (rounded for the sake simplicity). 
- we have 37500 in our payment address in 1 big unspent tx
- we have maxBlocksPerPayment = 1
- split the amount we have available in max payments available => split it in 3 
- send 1 block reward as payment to miners
- send 1 block reward for future payments to a random address from our wallet (or from an address taken from config)
- the remaining 1 block to another random address  (just like the one before)
- after this transaction we will have 2 TXs ready to be spent after X confirmations
- this would lead to faster payments 

this is just an example. I hope i drawn it right. 

Without an unshield limit we might have 5-8-10 (maybe more) blocks rewards unshielded at once on coins that have low blocktime. 
That's one tx from Z to T. When a part of it is spent, the remaining is sent to another address -> wait for min conf(delaying the payment) -> spend funds -> wait again -> spend funds -> wait again -> and so on.

**Comment by faneaatiku** [comment]
The issue I was trying to solve with this implementation was the delay of payments. This is solved by removing the maximum unshielding "if" statement. 

Closing.
